# Versão Docker Compose
version: '3.3'

# Serviços da minha aplicação
# Ele está indentado por ser um objeto (YAML/YML)
services:
  # Container de MySQL
  db: 
    # FROM mysql:5.7
    image: mysql:5.7 
    # Volume para os dados serem salvos
    # No caso seria uma lista de volumes
    volumes:
      - db_data:/var/lib/mysql
    # Todas as alterações serem atualizadas automaticamente
    restart: always
    # Configuração do banco de dados
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: kaiobispo
      MYSQL_PASSWORD: p@ssword

  # Configuração do workpress, que seria nossa aplicação WEB
  wordpress:
    # Quais serviços que o WordPress depende
    depends_on:
      - db
    # A imagem que vou utilizar
    image: wordpress:latest
    # Expondo a porta
    ports:
     - "8000:80"
    # Sempre que alterar ele irá atualizar
    restart: always
    # Configurações de acesso ao banco de dados
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: kaiobispo
      WORDPRESS_DB_PASSWORD: p@ssword
      WORDPRESS_DB_NAME: wordpress

# Salvar dentro do volume
volumes:
  db_data: {}