version: '3.3'

services:
  db:
    build: ./mysql/
    image: kaiobispo/compose_repository:mysqlcontainer1.0
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema..sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    build: ./flask/
    depends_on:
      - db
    image: kaiobispo/compose_repository:flaskcontainer1.0
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - "C:\\Users\\kaio4\\Documents\\curso_docker\\compose\\6_bind_mount_compose\\flask:/app"
    networks:
     - dockercompose

networks:
  dockercompose: